spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bitespeed_db
    username: root
    password: Loki@2316
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}